server:
  port: 9004
spring:
  application:
    name: ssmp-wx-api-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 9c33092e-e975-4e14-a8b7-d874b4a11b17
        group: ssmp-wx
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    url: jdbc:mysql://localhost:3306/ssmp-wx?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1994

sms:
  secretId: AKIDNVDg04Z0atv0rQh16uQm24oHYcPupLHw
  secretKey: ZS7VdqlSuGNEo84mDNbcNr5OTIqKbcMq
  appid: 1400489343
  sign: 贾志新个人使用