server:
  port: 9001

cos:
  app_id: 1259453839
  secret_id: AKIDT9ajeMq63mHsDLAuI7VebFivrZAplanV
  secret_key: gGagjWKsyEEH4Lq5Ua4oXx93nIaeNaYG
  bucket_name: lullaby-1259453839
  region: ap-nanjing
  domain: https://lullaby-1259453839.cos.ap-nanjing.myqcloud.com

spring:
  application:
    name: ssmp-wx-api
  servlet:
    multipart:
      max-file-size: 1024000000
      max-request-size: 4096000000
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        namespace: 9c33092e-e975-4e14-a8b7-d874b4a11b17
        group: ssmp-wx
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    url: jdbc:mysql://localhost:3306/ssmp-wx?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1994
    # type: com.alibaba.druid.pool.DruidDataSource
  # thymeleaf
  thymeleaf:
    prefix: classpath:/static/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false
  redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId: wxb9c84ec2e5c72d28 # 第一个公众号的appid
        secret: 23571b6925227e41a79345ae294a0fc2 # 公众号的appsecret
        token: 111 # 接口配置里的Token值
        aesKey: fx3qMEfJQXQQpUtRdpLMDySLdiXLYpoqmxXllS0er8A # 接口配置里的EncodingAESKey值

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000