server:
  port: 8888

spring:
  application:
    name: ssmp-wx-task
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 9c33092e-e975-4e14-a8b7-d874b4a11b17
        group: ssmp-wx

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

logging:
  level:
    org:
      springframework:
        cloud:
          task: debug
